// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Payment.Models;

namespace Payment.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    partial class PaymentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Payment.Models.PaymentState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PPID")
                        .HasColumnName("PPID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProcessPaymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .HasColumnName("State")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProcessPaymentId");

                    b.ToTable("PaymentState");
                });

            modelBuilder.Entity("Payment.Models.ProcessPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnName("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("CardHolder")
                        .HasColumnName("CardHolder")
                        .HasColumnType("text");

                    b.Property<string>("CreditCardNumber")
                        .HasColumnName("CreditCardNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnName("ExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SecurityCode")
                        .HasColumnName("SecurityCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProcessPayment");
                });

            modelBuilder.Entity("Payment.Models.PaymentState", b =>
                {
                    b.HasOne("Payment.Models.ProcessPayment", "ProcessPayment")
                        .WithMany()
                        .HasForeignKey("ProcessPaymentId");
                });
#pragma warning restore 612, 618
        }
    }
}
